package com.example.phonesexpertsystem

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize
//класс телефона
data class Phone(
    var name: String?,
    var price: Int?,
    var type: String?,
    var ram: Int?,
    var battery: Int?,
    var camera: Int?,
    var color: String?,
    var hasNFC: Boolean?,
    var hasFingerprint: Boolean?,
    var hasSD: Boolean?
)
@Parcelize
//класс характеристик получаемых от пользователя
data class PhoneCharacteristics(
    var name: String?,
    var price: String?,
    var type: String?,
    var ram: String?,
    var battery: String?,
    var camera: String?,
    var color: String?,
    var hasNFC: Boolean?,
    var hasFingerprint: Boolean?,
    var hasSD: Boolean?
):Parcelable

//база данных - массив элементов класса PHone
val base = listOf(
    Phone(
        "iPhone 7",
        15999,
        "Смартфон",
        32,
        1700,
        6,
        "Синий",
        hasNFC = false,
        hasFingerprint = false,
        hasSD = false
    ), Phone(
        "iPhone 7+",
        18999,
        "Смартфон",
        64,
        3900,
        8,
        "Красный",
        hasNFC = false,
        hasFingerprint = false,
        hasSD = false
    ), Phone(
        "iPhone 8",
        32900,
        "Смартфон",
        64,
        1875,
        12,
        "Синий",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone 8+",
        43990,
        "Смартфон",
        64,
        1900,
        12,
        "Золотистый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone Xr",
        54499,
        "Смартфон",
        128,
        3100,
        12,
        "Золотистый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone Xr",
        54390,
        "Смартфон",
        128,
        3100,
        12,
        "Серебристый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone Xs",
        62399,
        "Смартфон",
        128,
        3100,
        12,
        "Розовый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "iPhone Xr max",
        69799,
        "Смартфон",
        256,
        3200,
        12,
        "Золотистый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone 11",
        73990,
        "Смартфон",
        128,
        3110,
        12,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone 11",
        74299,
        "Смартфон",
        128,
        3110,
        12,
        "Серый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone 11 Pro Max",
        91890,
        "Смартфон",
        128,
        3110,
        12,
        "Красный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone 11",
        99999,
        "Смартфон",
        256,
        3969,
        12,
        "Серебристый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone 11 Pro Max",
        93999,
        "Смартфон",
        512,
        3969,
        12,
        "Синий",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone 12 Mini",
        74999,
        "Смартфон",
        64,
        2227,
        12,
        "Золотистый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone 12",
        94999,
        "Смартфон",
        128,
        2800,
        12,
        "Белый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone 12 Pro Max",
        132999,
        "Смартфон",
        256,
        3690,
        12,
        "Синий",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone 13 Mini",
        97999,
        "Смартфон",
        128,
        2300,
        12,
        "Красный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone 13",
        121999,
        "Смартфон",
        256,
        3700,
        12,
        "Голубой",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "iPhone 13 Pro Max",
        199999,
        "Смартфон",
        512,
        3700,
        12,
        "Золотистый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "Samsung A20",
        12999,
        "Смартфон",
        32,
        4000,
        13,
        "Чёрный",
        hasNFC = false,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung A20S",
        16999,
        "Смартфон",
        64,
        4000,
        13,
        "Красный",
        hasNFC = false,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung A22",
        24499,
        "Смартфон",
        128,
        4000,
        48,
        "Голубой",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung A22S",
        22999,
        "Смартфон",
        128,
        4000,
        48,
        "Белый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung A32",
        34999,
        "Смартфон",
        128,
        5000,
        48,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung A41",
        20499,
        "Смартфон",
        64,
        3500,
        48,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung A52",
        37999,
        "Смартфон",
        128,
        4500,
        48,
        "Красный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung A52",
        43999,
        "Смартфон",
        256,
        4500,
        64,
        "Голубой",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S9",
        24999,
        "Смартфон",
        64,
        3500,
        12,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "Samsung S9",
        30999,
        "Смартфон",
        128,
        3500,
        12,
        "Градиент",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "Samsung S10",
        30999,
        "Смартфон",
        128,
        3400,
        16,
        "Белый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S10e",
        59999,
        "Смартфон",
        128,
        3200,
        16,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S10+",
        69999,
        "Смартфон",
        128,
        4100,
        16,
        "Красный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S20 FE",
        59999,
        "Смартфон",
        128,
        4500,
        12,
        "Розовый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S20 FE",
        66999,
        "Смартфон",
        256,
        4500,
        12,
        "Серый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S20+",
        74999,
        "Смартфон",
        128,
        4500,
        64,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S20",
        69999,
        "Смартфон",
        128,
        4000,
        64,
        "Желтый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S20 Ultra",
        97899,
        "Смартфон",
        128,
        5000,
        108,
        "Розовый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S21",
        84899,
        "Смартфон",
        256,
        4000,
        64,
        "Голубой",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S21 FE",
        71999,
        "Смартфон",
        128,
        4500,
        12,
        "Cерый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S21+",
        108999,
        "Смартфон",
        128,
        4800,
        64,
        "Зеленый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S21 Ultra",
        137999,
        "Смартфон",
        512,
        5000,
        108,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S21",
        79999,
        "Смартфон",
        128,
        4000,
        64,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S22",
        99999,
        "Смартфон",
        128,
        3700,
        50,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Samsung S22 Ultra",
        149999,
        "Смартфон",
        512,
        5000,
        108,
        "Бордовый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Philips E590",
        5999,
        "Кнопочный",
        1,
        3100,
        2,
        "Белый",
        hasNFC = false,
        hasFingerprint = false,
        hasSD = true
    ), Phone(
        "teXet Tm-530R",
        3999,
        "Кнопочный",
        0,
        3500,
        0,
        "Чёрный",
        hasNFC = false,
        hasFingerprint = false,
        hasSD = true
    ), Phone(
        "Panasonic KX-TU456",
        5999,
        "Кнопочный",
        0,
        1000,
        0,
        "Красный",
        hasNFC = false,
        hasFingerprint = false,
        hasSD = true
    ), Phone(
        "Nokia 105SS",
        1899,
        "Кнопочный",
        0,
        800,
        0,
        "Чёрный",
        hasNFC = false,
        hasFingerprint = false,
        hasSD = true
    ), Phone(
        "Nokia 230 Dual SIM",
        4599,
        "Кнопочный",
        0,
        1200,
        0,
        "Синий",
        hasNFC = false,
        hasFingerprint = false,
        hasSD = true
    ), Phone(
        "Nokia 6300",
        6299,
        "Кнопочный",
        0,
        1500,
        1,
        "Фиолетовый",
        hasNFC = false,
        hasFingerprint = false,
        hasSD = true
    ),
    Phone(
        "Huawei Y5 Lite",
        5999,
        "Смартфон",
        16,
        3020,
        8,
        "Синий",
        hasNFC = false,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Huawei Y8p",
        17499,
        "Смартфон",
        128,
        4000,
        48,
        "Синий",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Huawei Y5p",
        8250,
        "Смартфон",
        128,
        3020,
        8,
        "Чёрный",
        hasNFC = false,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Huawei Y6p",
        11699,
        "Смартфон",
        64,
        5000,
        13,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Huawei nova 5T",
        27999,
        "Смартфон",
        128,
        3750,
        48,
        "Голубой",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Huawei P30",
        34999,
        "Смартфон",
        128,
        3650,
        40,
        "Голубой",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Huawei P40 Lite",
        20599,
        "Смартфон",
        128,
        4200,
        48,
        "Зеленый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Huawei P Smart",
        16999,
        "Смартфон",
        128,
        5000,
        48,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Huawei nova 8i",
        26999,
        "Смартфон",
        128,
        4300,
        64,
        "Серебристый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Huawei nova 8",
        29999,
        "Смартфон",
        128,
        3800,
        64,
        "Серебристый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Huawei P40",
        49999,
        "Смартфон",
        128,
        3800,
        50,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi Redmi 9A",
        10999,
        "Смартфон",
        128,
        5000,
        13,
        "Серый",
        hasNFC = false,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi Redmi 9C NFC",
        14999,
        "Смартфон",
        64,
        5000,
        13,
        "Серый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi Redmi 9A",
        23999,
        "Смартфон",
        64,
        5000,
        50,
        "Белый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = false
    ), Phone(
        "Xiaomi Redmi 9A",
        25999,
        "Смартфон",
        128,
        5000,
        64,
        "Синий",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi Redmi Note 11",
        25999,
        "Смартфон",
        128,
        5000,
        50,
        "Синий",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi Redmi Note 10 Pro",
        32999,
        "Смартфон",
        128,
        5000,
        108,
        "Бронзовый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi 11 Lite 5G NE",
        34999,
        "Смартфон",
        128,
        4250,
        64,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi 11 Lite 5G NE",
        34999,
        "Смартфон",
        128,
        4250,
        64,
        "Белый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi 11 Lite 5G NE",
        39999,
        "Смартфон",
        256,
        4250,
        64,
        "Белый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi 11T",
        44999,
        "Смартфон",
        128,
        5000,
        108,
        "Белый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi 11T",
        49999,
        "Смартфон",
        256,
        5000,
        108,
        "Белый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi 11T Pro",
        53999,
        "Смартфон",
        128,
        5000,
        108,
        "Белый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi 11T Pro",
        59999,
        "Смартфон",
        256,
        5000,
        108,
        "Белый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Xiaomi Mi 11",
        79995,
        "Смартфон",
        128,
        4600,
        108,
        "Серый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Honor 8A Prime",
        9999,
        "Смартфон",
        64,
        3020,
        13,
        "Синий",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Honor 20",
        24999,
        "Смартфон",
        128,
        3750,
        48,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Honor 30S",
        27999,
        "Смартфон",
        128,
        4000,
        64,
        "Серебристый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Honor 50 Lite",
        31999,
        "Смартфон",
        128,
        4300,
        40,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Honor 30 Premium",
        31999,
        "Смартфон",
        256,
        4000,
        40,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Honor 50",
        36999,
        "Смартфон",
        128,
        4300,
        108,
        "Зеленый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Honor 50",
        36999,
        "Смартфон",
        128,
        4300,
        108,
        "Зеленый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Honor 50",
        44999,
        "Смартфон",
        256,
        4300,
        108,
        "Серебристый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Honor 30 Pro+",
        54999,
        "Смартфон",
        256,
        4000,
        40,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "OPPO A16",
        14999,
        "Смартфон",
        32,
        5000,
        13,
        "Голубой",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "OPPO A54",
        14999,
        "Смартфон",
        64,
        5000,
        13,
        "Синий",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "OPPO A55",
        18999,
        "Смартфон",
        64,
        5000,
        50,
        "Чёрный",
        hasNFC = false,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "OPPO A54",
        19599,
        "Смартфон",
        128,
        5000,
        13,
        "Синий",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "OPPO A55",
        20699,
        "Смартфон",
        128,
        5000,
        50,
        "Чёрный",
        hasNFC = false,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "OPPO A74",
        22999,
        "Смартфон",
        128,
        5000,
        48,
        "Чёрный",
        hasNFC = false,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "OPPO Reno 5 Lite",
        26799,
        "Смартфон",
        128,
        4310,
        48,
        "Фиолетовый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "OPPO Reno 5",
        30899,
        "Смартфон",
        128,
        4310,
        64,
        "Серебристый",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Vivo Y1S",
        8499,
        "Смартфон",
        32,
        4030,
        13,
        "Чёрный",
        hasNFC = false,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Vivo Y21",
        17299,
        "Смартфон",
        64,
        5000,
        13,
        "Синий",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Vivo Y31",
        19199,
        "Смартфон",
        64,
        5000,
        48,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Vivo Y31",
        20399,
        "Смартфон",
        128,
        5000,
        48,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Vivo Y33s",
        23999,
        "Смартфон",
        128,
        5000,
        50,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Vivo V21E",
        25999,
        "Смартфон",
        128,
        4000,
        64,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Vivo V23e",
        35999,
        "Смартфон",
        128,
        4050,
        64,
        "Голубой",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    ), Phone(
        "Vivo V23 5G",
        49199,
        "Смартфон",
        128,
        4200,
        64,
        "Чёрный",
        hasNFC = true,
        hasFingerprint = true,
        hasSD = true
    )

)